//
//  TermsAndConditions.swift
//  Frood
//
//  Created by Mohammad Shariq on 08/05/25.
//

import SwiftUI

struct TermsAndConditions: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        ZStack {
            LinearGradient(
                gradient: Gradient(colors: [
                    Color(red: 86/255, green: 10/255, blue: 88/255),
                    Color(red: 130/255, green: 33/255, blue: 212/255)
                ]),
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()
            
            VStack(alignment: .leading, spacing: 16) {
                HStack {
                    Button(action: {
                        dismiss()
                    }) {
                        Image(systemName: "arrow.backward")
                            .foregroundColor(.white)
                    }
                    Text("Terms and Conditions")
                        .foregroundColor(.white)
                        .font(.headline)
                        Spacer()
                }
                .padding()
                ScrollView {
                    VStack(spacing: 0) {
                        Image("terms")
                            .resizable()
                            .scaledToFit()
                            .frame(maxWidth: .infinity)
        
                        Spacer().frame(height: 20)
                        Text("Version 1.1\nLast updated: 8th May 2025")
                            .foregroundColor(.white)
                            .font(.footnote)
                            .multilineTextAlignment(.leading)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.horizontal)
                            
                        
                        Text("""
                       This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                       """)
                        .foregroundColor(.white)
                        .font(.footnote)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal)
                        .padding(.top,20)
                        
                        Text("""
                       This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                       """)
                        .foregroundColor(.white)
                        .font(.footnote)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal)
                        .padding(.top,20)
                        
                        Text("""
                       This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                       """)
                        .foregroundColor(.white)
                        .font(.footnote)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal)
                        .padding(.top,20)
                        
                        Text("""
                       This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                       """)
                        .foregroundColor(.white)
                        .font(.footnote)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal)
                        .padding(.top,20)
                        
                        Text("""
                       This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
                       """)
                        .foregroundColor(.white)
                        .font(.footnote)
                        .multilineTextAlignment(.leading)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.horizontal)
                        .padding(.top,20)
                    }
                }
            }
            .navigationBarBackButtonHidden(true)
        }
    }
}

#Preview {
    TermsAndConditions()
}
